- 👋 Hi, I’m @S92068218
- 👀 I’m interested in Writing quotes
- 🌱 I’m currently learning ...BSE Degree
- 💞️ I’m looking to collaborate on ...study program and project submission
- 📫 How to reach me ...by the way i work hard

<!---
S92068218/S92068218 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
